# Deep Learning

## ANN Regression
Artificial Neural Network Regression model to predict the electrical energy output of a Combined Cycle Power Plant

#### Implement the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

### Part 1 - Data Preprocessing

#### Import the dataset

In [2]:
dataset = pd.read_excel('Folds5x2_pp.xlsx', engine='openpyxl')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [4]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


#### Split dataset into training and test set

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Part 2 - Building the ANN

#### Initializing the ANN

In [6]:
ann = tf.keras.models.Sequential()

#### Adding the Input Layer and the First Hidden Layer

In [7]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the Second Hidden Layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the Output Layer

In [9]:
ann.add(tf.keras.layers.Dense(units=1))

### Part 3 - Training the ANN

#### Compiling the ANN

In [10]:
ann.compile(optimizer='adam', loss='mean_squared_error')

#### Training the ANN on the training set

In [11]:
ann.fit(x=X_train, y=y_train, epochs=100, batch_size=32)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 144789.1556
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 603.7775

#### Predict the results of the Test set

In [12]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[432.61 431.23]
 [463.69 460.01]
 [467.2  461.14]
 ...
 [474.44 473.26]
 [441.14 438.  ]
 [460.39 463.28]]
